package com.soll.ui.theme

import androidx.compose.ui.graphics.Color

// Primary - Teal/Aqua theme (from IVARO)
val md_theme_light_primary = Color(0xFF006A67)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF8DEFEA)
val md_theme_light_onPrimaryContainer = Color(0xFF00201F)
val md_theme_light_secondary = Color(0xFF4A6362)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCE8E6)
val md_theme_light_onSecondaryContainer = Color(0xFF051F1F)
val md_theme_light_tertiary = Color(0xFF4B607C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD3E4FF)
val md_theme_light_onTertiaryContainer = Color(0xFF041C35)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFC)
val md_theme_light_onBackground = Color(0xFF191C1C)
val md_theme_light_surface = Color(0xFFFAFDFC)
val md_theme_light_onSurface = Color(0xFF191C1C)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E3)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4948)
val md_theme_light_outline = Color(0xFF6F7978)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F0)
val md_theme_light_inverseSurface = Color(0xFF2D3130)
val md_theme_light_inversePrimary = Color(0xFF52DAD4)

val md_theme_dark_primary = Color(0xFF52DAD4)
val md_theme_dark_onPrimary = Color(0xFF003735)
val md_theme_dark_primaryContainer = Color(0xFF004A47)
val md_theme_dark_onPrimaryContainer = Color(0xFF8DEFEA)
val md_theme_dark_secondary = Color(0xFFB0CCCA)
val md_theme_dark_onSecondary = Color(0xFF1B3534)
val md_theme_dark_secondaryContainer = Color(0xFF324B4A)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCE8E6)
val md_theme_dark_tertiary = Color(0xFFB5C7E9)
val md_theme_dark_onTertiary = Color(0xFF1E314B)
val md_theme_dark_tertiaryContainer = Color(0xFF354863)
val md_theme_dark_onTertiaryContainer = Color(0xFFD3E4FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1C)
val md_theme_dark_onBackground = Color(0xFFE0E3E2)
val md_theme_dark_surface = Color(0xFF191C1C)
val md_theme_dark_onSurface = Color(0xFFE0E3E2)
val md_theme_dark_surfaceVariant = Color(0xFF3F4948)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C7)
val md_theme_dark_outline = Color(0xFF889391)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1C)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E2)
val md_theme_dark_inversePrimary = Color(0xFF006A67)

// Status Colors
val StatusRunning = Color(0xFF2E7D32)
val StatusStopped = Color(0xFF9E9E9E)
val StatusError = Color(0xFFD32F2F)
val StatusWarning = Color(0xFFF57C00)
val StatusPending = Color(0xFF0288D1)
